Update docker-image.yml

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -2,45 +2,46 @@ name: Docker Image CI
 
 on:
   push:
-    branches: [ "main" ]
+    branches: ["main"]
   pull_request:
-    branches: [ "main" ]
+    branches: ["main"]
 
 jobs:
   build:
     runs-on: ubuntu-latest
 
     steps:
-    # Checkout the repository
-    - uses: actions/checkout@v4
+      # Checkout the repository
+      - uses: actions/checkout@v4
 
-    # Set up Docker Buildx for multi-platform builds
-    - name: Set up Docker Buildx
-      uses: docker/setup-buildx-action@v2
+      # Set up Docker Buildx for multi-platform builds
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v2
 
-    # Log in to Docker Hub using stored secrets
-    - name: Log in to Docker Hub
-      uses: docker/login-action@v2
-      with:
-        username: ${{ secrets.DOCKER_USERNAME }}
-        password: ${{ secrets.DOCKER_PASSWORD }}
+      # Log in to Docker Hub using stored secrets
+      - name: Log in to Docker Hub
+        uses: docker/login-action@v2
+        with:
+          username: ${{ secrets.DOCKER_USERNAME }}
+          password: ${{ secrets.DOCKER_PASSWORD }}
 
-    # Pull base image if it already exists (optional step)
-    - name: Pull base image
-      run: docker pull cyriljose/interactive_qa_bot:1.0 || true  # Fails gracefully if image doesn't exist
+      # Pull base image if it already exists (optional step)
+      - name: Pull base image
+        run: docker pull cyriljose/interactive_qa_bot:1.0 || true  # Fails gracefully if image doesn't exist
 
-    # Build the Docker image using caching
-    - name: Build the Docker image
-      run: |
-        docker buildx create --use
-        docker buildx build \
-          --file Interactive_QA_Bot_Interface/Dockerfile \
-          --tag cyriljose/interactive_qa_bot:1.0 \
-          --push .
+      # Build the Docker image using caching
+      - name: Build the Docker image
+        run: |
+          docker buildx create --use
+          docker buildx build \
+            --file Interactive_QA_Bot_Interface/Dockerfile \
+            --tag cyriljose/interactive_qa_bot:1.0 \
+            --push \
+            .
 
-    # Push the Docker image to Docker Hub
-    - name: Push the Docker image
-      run: docker push cyriljose/interactive_qa_bot:1.0
+      # Push the Docker image to Docker Hub
+      - name: Push the Docker image
+        run: docker push cyriljose/interactive_qa_bot:1.0
 
     # Log out from Docker Hub
     - name: Log out of Docker Hub
